webtruyen:
  build: .
  dockerfile: ./docker/Dockerfile
  container_name: webtruyen_container
  working_dir: /var/www/html
  ports:
    - "80:80"
  volumes:
    - .:/var/www/html
    - ./docker/nginx-log:/var/log/nginx
    - ./docker/php-fpm/php-fpm.log:/var/log/php-fpm.log
    - ./docker/config/app.conf:/etc/nginx/conf.d/app.conf
    - ./storage:/var/www/html/storage
    - ./public/images:/var/www/public/images
  links:
    - mysql

mysql:
  image: mysql:8.0.31
  container_name: webtruyen_mysql
  ports:
    - "3306:3306"
  volumes:
    - ./docker/mysql:/var/lib/mysql
  environment:
    MYSQL_DATABASE: webtruyen
    MYSQL_ROOT_PASSWORD: webtruyen
